server:
  port: 8080

spring:
  application:
    name: videoapp
  datasource:
    url: jdbc:mysql://localhost:3307/videoapp
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 360000

outbound:
  chatapp:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: "http://localhost:5173/auth/google"
